<?php
/** License choices from the reference landing page. */
defined( 'ABSPATH' ) || exit;
$shop_url = function_exists( 'wc_get_page_permalink' ) ? wc_get_page_permalink( 'shop' ) : home_url( '/shop/' );
$theme_term  = function_exists( 'get_term_by' ) ? get_term_by( 'slug', 'wordpress-themes', 'product_cat' ) : false;
$plugin_term = function_exists( 'get_term_by' ) ? get_term_by( 'slug', 'wordpress-plugins', 'product_cat' ) : false;
$theme_url   = $theme_term && ! is_wp_error( $theme_term ) ? get_term_link( $theme_term ) : $shop_url;
$plugin_url  = $plugin_term && ! is_wp_error( $plugin_term ) ? get_term_link( $plugin_term ) : $shop_url;
$theme_url   = is_wp_error( $theme_url ) ? $shop_url : $theme_url;
$plugin_url  = is_wp_error( $plugin_url ) ? $shop_url : $plugin_url;
?>
<section class="wpp-licensing mx-auto mt-24 max-w-[1200px] px-4 sm:px-6">
	<header class="text-center"><h2 class="text-3xl font-bold tracking-tight sm:text-[40px] sm:leading-[1.1]"><?php esc_html_e( 'Прозрачные условия', 'wp-panda' ); ?></h2><p class="mt-2 text-sm text-muted sm:text-base"><?php esc_html_e( 'Два простых формата покупки: темы на 1 или 5 сайтов, плагины — навсегда', 'wp-panda' ); ?></p></header>
	<div class="mt-10 grid gap-5 md:grid-cols-2">
		<article class="rounded-card border-2 border-brand bg-white p-7 shadow-picked"><span class="rounded-full bg-ink px-3 py-1 text-xs font-semibold text-white"><?php esc_html_e( 'Темы WordPress', 'wp-panda' ); ?></span><h3 class="mt-4 text-2xl font-bold tracking-tight"><?php esc_html_e( '1 сайт или 5 сайтов', 'wp-panda' ); ?></h3><p class="mt-2 text-sm text-muted"><?php esc_html_e( 'Каждая тема продаётся с выбором количества сайтов:', 'wp-panda' ); ?></p><div class="mt-6 space-y-3"><div class="flex items-center justify-between rounded-2xl bg-soft p-4"><div><div class="font-semibold text-ink"><?php esc_html_e( 'Личная лицензия', 'wp-panda' ); ?></div><div class="text-xs text-muted"><?php esc_html_e( 'Для одного собственного проекта', 'wp-panda' ); ?></div></div><strong class="text-sm">1 <?php esc_html_e( 'сайт', 'wp-panda' ); ?></strong></div><div class="flex items-center justify-between rounded-2xl bg-soft p-4"><div><div class="font-semibold text-ink"><?php esc_html_e( 'Студийная лицензия', 'wp-panda' ); ?></div><div class="text-xs text-muted"><?php esc_html_e( 'Для нескольких проектов', 'wp-panda' ); ?></div></div><strong class="text-sm">5 <?php esc_html_e( 'сайтов', 'wp-panda' ); ?></strong></div></div><a class="button button--brand button--large mt-6 w-full" href="<?php echo esc_url( $theme_url ); ?>"><?php esc_html_e( 'Выбрать тему', 'wp-panda' ); ?></a></article>
		<article class="dark-card flex flex-col justify-between rounded-card p-7 text-white shadow-float"><div><span class="rounded-full bg-brand px-3 py-1 text-xs font-bold text-ink"><?php esc_html_e( 'Плагины WordPress', 'wp-panda' ); ?></span><h3 class="mt-4 text-2xl font-bold tracking-tight text-white"><?php esc_html_e( 'Лицензия навсегда', 'wp-panda' ); ?></h3><p class="mt-2 text-sm text-white/70"><?php esc_html_e( 'Все плагины Wp Panda продаются с пожизненным доступом. Покупаете один раз — пользуетесь бессрочно.', 'wp-panda' ); ?></p><ul class="mt-6 space-y-3 text-sm text-white/85"><?php foreach ( array( __( 'Один платёж без ежегодных продлений', 'wp-panda' ), __( 'Все будущие обновления плагина включены', 'wp-panda' ), __( 'Неограниченное использование на ваших проектах', 'wp-panda' ), __( 'Техническая поддержка от разработчиков', 'wp-panda' ) ) as $item ) : ?><li class="flex items-center gap-2.5"><span class="flex h-5 w-5 flex-shrink-0 items-center justify-center rounded-full bg-brand text-xs font-bold text-ink">✓</span><?php echo esc_html( $item ); ?></li><?php endforeach; ?></ul></div><a class="button button--brand button--large mt-6 w-full" href="<?php echo esc_url( $plugin_url ); ?>"><?php esc_html_e( 'Выбрать плагин', 'wp-panda' ); ?></a></article>
	</div>
</section>
