<?php
/** Testimonials from the supplied static layout. */
defined( 'ABSPATH' ) || exit;
$quotes = array(
	array( 'quote' => 'Перенесли магазин на Vesta за выходные. Скорость выросла вдвое, а плагин WooBoost окупился в первый же день. Поддержка отвечает быстрее, чем я успеваю сварить кофе.', 'name' => 'Екатерина Лебедева', 'role' => 'Владелица магазина «Лён & Хлопок»', 'product' => 'Vesta + WooBoost', 'avatar' => 'https://images.pexels.com/photos/6497114/pexels-photo-6497114.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=160&h=160' ),
	array( 'quote' => 'Берём лицензии на 5 сайтов для клиентских проектов, а плагины навсегда — идеальная модель. Чистый код, понятная документация и честные обновления.', 'name' => 'Артём Николаев', 'role' => 'Основатель студии «Пиксель»', 'product' => 'Aurora · 5 сайтов', 'avatar' => 'https://images.pexels.com/photos/14950779/pexels-photo-14950779.jpeg?auto=compress&cs=tinysrgb&fit=crop&w=160&h=160' ),
	array( 'quote' => 'Сайт-портфолио с сотнями фото грузится меньше чем за секунду. Плагин один раз купил — и навсегда. Справился без разработчика.', 'name' => 'Тимур Алиев', 'role' => 'Фотограф, портфолио на Habitat', 'product' => 'Habitat + TurboCache', 'avatar' => 'https://images.pexels.com/photos/37273005/pexels-photo-37273005.png?auto=compress&cs=tinysrgb&fit=crop&w=160&h=160' ),
);
?>
<section class="wpp-testimonials mx-auto mt-24 max-w-[1200px] px-4 sm:px-6">
	<header class="text-center"><h2 class="text-3xl font-bold tracking-tight sm:text-[40px] sm:leading-[1.1]"><?php esc_html_e( 'Отзывы владельцев сайтов', 'wp-panda' ); ?></h2><p class="mt-2 text-sm text-muted sm:text-base"><?php esc_html_e( 'Реальный опыт людей, которые строят свои проекты на Wp Panda.', 'wp-panda' ); ?></p></header>
	<div class="mt-10 grid gap-5 md:grid-cols-3"><?php foreach ( $quotes as $quote ) : ?><figure class="flex flex-col rounded-card border border-line bg-white p-6 shadow-card"><div class="flex items-center justify-between gap-2"><span class="text-sm tracking-[0.12em] text-brand">★★★★★</span><span class="rounded-full bg-soft px-2.5 py-1 text-[11px] font-medium text-muted"><?php echo esc_html( $quote['product'] ); ?></span></div><blockquote class="mt-4 flex-1 text-[15px] leading-relaxed text-ink/85">«<?php echo esc_html( $quote['quote'] ); ?>»</blockquote><figcaption class="mt-6 flex items-center gap-3"><img src="<?php echo esc_url( $quote['avatar'] ); ?>" alt="" class="h-11 w-11 rounded-full object-cover" loading="lazy"><div><strong class="block text-sm font-semibold"><?php echo esc_html( $quote['name'] ); ?></strong><span class="block text-xs text-muted"><?php echo esc_html( $quote['role'] ); ?></span></div></figcaption></figure><?php endforeach; ?></div>
</section>
