<?php
/** Searchable category index backed by the imported KB page and child guides. */
defined( 'ABSPATH' ) || exit;
$data       = function_exists( 'wpp_demo_load_data' ) ? wpp_demo_load_data() : array();
$categories = array();
if ( is_array( $data ) && ! empty( $data['kb_articles'] ) ) {
	foreach ( $data['kb_articles'] as $article ) { $categories[ sanitize_title( $article['category'] ) ] = $article['category']; }
}
$popular_slugs = array( 'install-theme', 'demo-import', 'license-key', 'auto-updates' );
?>
<header class="knowledge-heading"><p class="eyebrow"><?php esc_html_e( 'Документация Wp Panda', 'wp-panda' ); ?></p><?php the_title( '<h1>', '</h1>' ); ?><p><?php esc_html_e( 'Пошаговые инструкции по установке, лицензиям, обновлениям и настройке продуктов.', 'wp-panda' ); ?></p></header>
<div class="kb-search"><label class="screen-reader-text" for="wpp-kb-search"><?php esc_html_e( 'Поиск по базе знаний', 'wp-panda' ); ?></label><span><?php echo wpp_icon( 'search', 'h-4 w-4' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></span><input id="wpp-kb-search" type="search" data-kb-search placeholder="<?php esc_attr_e( 'Что вы хотите найти?', 'wp-panda' ); ?>"></div>
<?php if ( $categories ) : ?><nav class="kb-filter" aria-label="<?php esc_attr_e( 'Категории базы знаний', 'wp-panda' ); ?>"><button type="button" class="is-active" data-kb-filter="all" aria-pressed="true"><?php esc_html_e( 'Все темы', 'wp-panda' ); ?></button><?php foreach ( $categories as $slug => $label ) : ?><button type="button" data-kb-filter="<?php echo esc_attr( $slug ); ?>" aria-pressed="false"><?php echo esc_html( $label ); ?></button><?php endforeach; ?></nav><?php endif; ?>
<?php if ( $popular_slugs && function_exists( 'wpp_demo_find_post_id' ) ) : ?><section class="kb-popular"><div><p class="eyebrow"><?php esc_html_e( 'Начните отсюда', 'wp-panda' ); ?></p><h2><?php esc_html_e( 'Популярные инструкции', 'wp-panda' ); ?></h2></div><ul><?php foreach ( $popular_slugs as $slug ) : ?><?php $article_id = wpp_demo_find_post_id( 'page', 'kb:' . $slug ); ?><?php if ( $article_id ) : ?><li><a href="<?php echo esc_url( get_permalink( $article_id ) ); ?>"><?php echo esc_html( get_the_title( $article_id ) ); ?> <?php echo wpp_icon( 'arrow', 'h-4 w-4' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></a></li><?php endif; ?><?php endforeach; ?></ul></section><?php endif; ?>
<div class="kb-content"><div class="entry-content prose-content" data-kb-content><?php the_content(); ?></div><p class="kb-no-results" data-kb-empty hidden><?php esc_html_e( 'Не нашли подходящую инструкцию. Попробуйте другой запрос или напишите в поддержку.', 'wp-panda' ); ?></p></div>
<section class="faq-help-cta"><div><p class="eyebrow"><?php esc_html_e( 'Не нашли ответ?', 'wp-panda' ); ?></p><h2><?php esc_html_e( 'Команда поддержки поможет с настройкой', 'wp-panda' ); ?></h2><p><?php esc_html_e( 'Если вопрос связан с покупкой, войдите в личный кабинет. По установке и настройке сначала проверьте инструкции выше.', 'wp-panda' ); ?></p></div><a class="button button--brand" href="<?php echo esc_url( function_exists( 'wc_get_page_permalink' ) ? wc_get_page_permalink( 'myaccount' ) : wp_login_url() ); ?>"><?php esc_html_e( 'Открыть личный кабинет', 'wp-panda' ); ?> <?php echo wpp_icon( 'arrow', 'h-4 w-4' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></a></section>
